### ISSUE TITLE
v1.0.1 TO-DO

### ISSUE THREAD

**Issue by GlacierShard92** [GlacierShard92/ErpeMcmmoMining#3]
- [ ] If someone has 0 breaks, display it as 0 and not as nothing.
- [x] Make it only able to get mining levels from mining stone
- [x] Add up to level 10 mining levels
- [x] add /mining [sub commands]

**Comment by GlacierShard92** [comment]
1/4 DONE :+1:

**Comment by GlacierShard92** [comment]
@applqpak can u do the first checkbox?

**Comment by GoldishKirby** [comment]
Use TextFormat than the MCPE Color Code.

Probably not a useful suggestion, but yeah.

**Comment by GlacierShard92** [comment]
im not a fan on TextFormat, its easier for me to use §

**Comment by GoldishKirby** [comment]
Okay.
